### ISSUE TITLE
Relations 

### ISSUE THREAD

**Issue by jpomal** [juliandragoi/GasSafeCertificate#1]
Hey Julian,

I was having a look at the structure of each table and I see that there are primary keys used, however, I'm pretty sure that there will need to be some foreign keys.

For example the Appliance and Appliance type tables 

The Appliance type needs to be referenced at the bottom of the Appliance Table

![screen shot 2018-06-28 at 00 32 43](https://user-images.githubusercontent.com/25250150/42005149-f7e582c6-7a6a-11e8-8c96-50967f35cfbf.png)

Is this yet to be implemented?

Jitz

**Comment by juliandragoi** [comment]
Hi Jitz

The foreign keys are yet to be implemented
This was the initial setup of the project
Next step would be to have the foreign keys put in and a transaction table

Thanks
Julian

**Comment by jpomal** [comment]
Hey Julian,

Okay yeah no worries.

I am going to have a deeper look into how each table will link to each other.
In order for me to do this do you have anything that you can send me describing what the end result of the product will be? Or an ERD diagram.

if you don't no worries ill try to create one and sent it to you.

Jitz

**Comment by juliandragoi** [comment]
Hi Jitz,

Ideally i want this to be a data warehouse. so the table already in the repo should be dimensions and then they should all link to one table (fact table)
I will send you and example in a separate email

Julian
